name: Docker Image CI

on:
  push:
    branches:
      - ci/changes
  pull_request:
    branches:
      - ci/changes

jobs:
  build:
    name: Build Docker Image v${{ steps.get_version.outputs.VERSION }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Read version
        id: get_version
        run: echo "::set-output name=VERSION::$(cat version.txt)"

      - name: Build Docker Image
        run: |
          docker build -t myapp:${{ steps.get_version.outputs.VERSION }} .

  test:
    name: Test Docker Image Health v${{ steps.get_version.outputs.VERSION }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Read version
        id: get_version
        run: echo "::set-output name=VERSION::$(cat version.txt)"

      - name: Run Docker Container
        run: |
          docker run -d -p 8080:80 --name myapp myapp:${{ steps.get_version.outputs.VERSION }}
          sleep 10

      - name: Test Health Endpoint
        run: |
          curl -f http://localhost:8080/health

      - name: Stop Docker Container
        run: |
          docker stop myapp
          docker rm myapp

  security_scan:
    name: Trivy Security Scan v${{ steps.get_version.outputs.VERSION }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Read version
        id: get_version
        run: echo "::set-output name=VERSION::$(cat version.txt)"

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Run Trivy Scan
        run: |
          trivy image myapp:${{ steps.get_version.outputs.VERSION }}

  push:
    name: Push Docker Image to DockerHub v${{ steps.get_version.outputs.VERSION }}
    runs-on: ubuntu-latest
    needs: [build, test, security_scan]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Read version
        id: get_version
        run: |
          VERSION=$(cat version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker tag myapp:${{ steps.get_version.outputs.VERSION }} ${{ secrets.DOCKER_USERNAME }}/myapp:${{ steps.get_version.outputs.VERSION }}
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:${{ steps.get_version.outputs.VERSION }}

