name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Read version
        id: get_version
        run: |
          VERSION=$(cat src/version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        run: |
          docker build -t fastapi:${{ steps.get_version.outputs.VERSION }} .

  test:
    name: Test Docker Image Health v${{ needs.build.outputs.VERSION }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Docker Container
        run: |
          docker run -d -p 8080:80 --name fastapi fastapi:${{ needs.build.outputs.VERSION }}
          sleep 10

      - name: Test Health Endpoint
        run: |
          curl -f http://localhost:8080/health

      - name: Stop Docker Container
        run: |
          docker stop fastapi
          docker rm fastapi

  security_scan:
    name: Trivy Security Scan v${{ needs.build.outputs.VERSION }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: fastapi:${{ needs.build.outputs.VERSION }}

  push:
    name: Push Docker Image to DockerHub v${{ needs.build.outputs.VERSION }}
    runs-on: ubuntu-latest
    needs: [build, test, security_scan]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker tag fastapi:${{ needs.build.outputs.VERSION }} ${{ secrets.DOCKER_USERNAME }}/fastapi:${{ needs.build.outputs.VERSION }}
          docker push ${{ secrets.DOCKER_USERNAME }}/fastapi:${{ needs.build.outputs.VERSION }}
